image: node:latest

cache:
  paths:
  - node_modules/

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
  artifacts:
    paths:
      - dist
  only:
    - master

test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - test
  only:
    - master

pages:
  stage: deploy
  script:
    - npm publish
  artifacts:
    paths:
      - public
  only:
    - master