image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm install

stages:
  - build
  - test
  - document

build:
  stage: build
  script:
    - npm dist
  artifacts:
    paths:
      - dist

test:
  stage: test
  script:
    - npm test
  artifacts:
    paths:
      - test

pages:
  stage: document
  script:
    - npm doc
  artifacts:
    paths:
      - public