image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm install

pages:
  stage: deploy
  script:
    - npm run build
    - npm run test
    - npm run deploy
  artifacts:
    paths:
      - public
  only:
    - master