image: node:latest

cache:
  paths:
  - node_modules/
  - dist/

before_script:
  - npm install

build:
  stage: build
  script:
    - gulp build
  artifacts:
    paths:
      - dist

test:
  stage: test
  script:
    - gulp test
  artifacts:
    paths:
      - test

pages:
  stage: document
  script:
    - gulp doc
  artifacts:
    paths:
      - public