image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm install

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm run-script build
  artifacts:
    paths:
      - dist
  only:
    - master

test:
  stage: test
  script:
    - npm run-script test
  artifacts:
    paths:
      - test
  only:
    - master

pages:
  stage: deploy
  script:
    - npm run-script deploy
  artifacts:
    paths:
      - public
  only:
    - master