image: node:latest

cache:
  paths:
  - node_modules/

before_script:
  - npm install

test:
  stage: test
  script:
  - gulp test

pages:
  stage: deploy
  script:
  - gulp doc
  artifacts:
    paths:
    - public