image: node:latest

tags:
  - docker
  - node

cache:
  paths:
  - node_modules/

before_script:
  - npm install

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - master

test:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - test
  only:
    - master

pages:
  stage: deploy
  script:
    - npm run deploy
  artifacts:
    paths:
      - public
  only:
    - master